### ISSUE TITLE
We should allow user input options for all params of search_Posts API call

### ISSUE THREAD

**Issue by andewmark** [Team-Mission-Blue/MissionBlueAPI#12]
We should probably use [click ](https://click.palletsprojects.com/en/stable/)for this

**Comment by Lementknight** [comment]
Nice idea, @andewmark!

**Comment by Lementknight** [comment]
@andewmark by all params you are referring to the ones in the app.bsky.feed.searchPosts() method correct?
```
app.bsky.feed.searchPosts()
```
https://docs.bsky.app/docs/api/app-bsky-feed-search-posts

**Comment by Lementknight** [comment]
This is correct, linking merge request now

@andewmark
